FTL_HRMS/Models/Hr/Designation.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FTL_HRMS.Models.Hr
{
    [Table("tbl_Designation")]
    public class Designation
    {
        [Key]
        public int Sl { get; set; }

        public string Code { get; set; }

        [Required(ErrorMessage = "Name cannot be empty")]
        [MaxLength(250)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Department cannot be empty")]
        [ForeignKey("Department")]
        public int DepartmentId { get; set; }

        [Required(ErrorMessage = "Role Name cannot be empty")]
        public string RoleName { get; set; }

        [ForeignKey("CreateEmployee")]
        public int? CreatedBy { get; set; }

        [DataType(DataType.Date),
        DisplayFormat(DataFormatString = "{0:dd-MM-yy}",
        ApplyFormatInEditMode = true)]
        public DateTime CreateDate { get; set; }

        [ForeignKey("UpdateEmployee")]
        public int? UpdatedBy { get; set; }

        [DataType(DataType.Date),
        DisplayFormat(DataFormatString = "{0:dd-MM-yy}",
        ApplyFormatInEditMode = true)]
        public DateTime? UpdateDate { get; set; }

        [DefaultValue(true)]
        public bool Status { get; set; }
        
        public virtual Employee CreateEmployee { get; set; }
        public virtual Employee UpdateEmployee { get; set; }
        public virtual Department Department { get; set; }
    }
}

FTL_HRMS/Controllers/DesignationsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FTL_HRMS.DAL;
using FTL_HRMS.Models.Hr;
using FTL_HRMS.Utility;
using Microsoft.AspNet.Identity.EntityFramework;

namespace FTL_HRMS.Controllers
{
    public class DesignationsController : Controller
    {
        private HRMSDbContext _db = new HRMSDbContext();

        #region List
        // GET: Designations
        public ActionResult Index()
        {
            return View(_db.Designation.Include(i => i.Department).Include(a => a.CreateEmployee).Include(a => a.UpdateEmployee).Where(i => i.Status == true).ToList());
        }
        #endregion

        #region Details
        // GET: Designations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Designation designation = _db.Designation.Find(id);
            if (designation == null)
            {
                return HttpNotFound();
            }
            return View(designation);
        }
        #endregion

        #region Get Designations By Department
        public ActionResult GetDesignationByDeptId()
        {
            int departmentId;
            Int32.TryParse(Request["DepartmentId"],out departmentId);
            var s = from p in _db.Designation.AsEnumerable()
                    where p.DepartmentId == departmentId
                    select new Designation { Sl = p.Sl, Name = p.Name };
            return Json(s, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Create
        // GET: Designations/Create
        public ActionResult Create()
        {
            List<DepartmentGroup> departmentGroupList = new List<DepartmentGroup>();
            departmentGroupList = _db.DepartmentGroup.Where(i => i.Status == true).ToList();
            ViewBag.DepartmentGroupId = new SelectList(departmentGroupList, "Sl", "Name");

            List<IdentityRole> roleList = new List<IdentityRole>();
            roleList = _db.Roles.Where(i => i.Name != "System Admin" && i.Name != "Super Admin").ToList();
            ViewBag.RoleName = new SelectList(roleList, "Name", "Name");

            return View();
        }

        // POST: Designations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,Code,Name,DepartmentId,RoleName,CreatedBy,CreateDate,UpdatedBy,UpdateDate,Status")] Designation designation)
        {
            if (_db.Designation.Where(i => i.Code == designation.Code).ToList().Count < 1)
            {
                if (_db.Designation.Where(i => i.Name == designation.Name && i.DepartmentId == designation.DepartmentId).ToList().Count < 1)
                {
                    string userName = User.Identity.Name;
                    int userId = DbUtility.GetUserId(_db, userName);
                    designation.CreatedBy = userId;
                    designation.CreateDate = Utility.Utility.GetCurrentDateTime();
                    designation.DepartmentId = Convert.ToInt32(Request["ddl_dept"]);
                    designation.Status = true;
                    _db.Designation.Add(designation);
                    _db.SaveChanges();
                    TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.AddSuccess);
                    return RedirectToAction("Create");
                }
                else
                {
                    TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.NameExist);
                }
            }
            else
            {
                TempData["message"] =DbUtility.GetStatusMessage(DbUtility.Status.CodeExist);
            }
            List<DepartmentGroup> departmentGroupList = new List<DepartmentGroup>();
            departmentGroupList = _db.DepartmentGroup.Where(i => i.Status == true).ToList();
            ViewBag.DepartmentGroupId = new SelectList(departmentGroupList, "Sl", "Name");
            List<IdentityRole> roleList = new List<IdentityRole>();
            roleList = _db.Roles.Where(i => i.Name != "System Admin" && i.Name != "Super Admin").ToList();
            ViewBag.RoleName = new SelectList(roleList, "Name", "Name");
            return View(designation);
        }
        #endregion

        #region Edit
        // GET: Designations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Designation designation = _db.Designation.Find(id);
            if (designation == null)
            {
                return HttpNotFound();
            }

            int departmentId = _db.Designation.Where(x => x.Sl == designation.Sl).Select(t => t.DepartmentId).FirstOrDefault();
            ViewBag.DepartmentId = _db.Department.Where(x => x.Sl == departmentId).Select(t => t.Sl).FirstOrDefault();
            ViewBag.DepartmentName = _db.Department.Where(x => x.Sl == departmentId).Select(t => t.Name).FirstOrDefault();
            int departmentGroupId = _db.Department.Where(x => x.Sl == departmentId).Select(t => t.DepartmentGroupId).FirstOrDefault();

            List<DepartmentGroup> departmentGroupList = new List<DepartmentGroup>();
            departmentGroupList = _db.DepartmentGroup.Where(i => i.Status == true).ToList();
            ViewBag.DepartmentGroupId = new SelectList(departmentGroupList, "Sl", "Name", departmentGroupId);

            List<IdentityRole> roleList = new List<IdentityRole>();
            roleList = _db.Roles.Where(i => i.Name != "System Admin" && i.Name != "Super Admin").ToList();
            ViewBag.RoleName = new SelectList(roleList, "Name", "Name", designation.RoleName);
            return View(designation);
        }

        // POST: Designations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,Code,Name,DepartmentId,RoleName,CreatedBy,CreateDate,UpdatedBy,UpdateDate,Status")] Designation designation)
        {
            List<DepartmentGroup> departmentGroupList = new List<DepartmentGroup>();
            departmentGroupList = _db.DepartmentGroup.Where(i => i.Status == true).ToList();
            List<IdentityRole> roleList = new List<IdentityRole>();
            roleList = _db.Roles.Where(i => i.Name != "System Admin" && i.Name != "Super Admin").ToList();
            if (_db.Designation.Where(i => i.Sl == designation.Sl).Select(i => i.Code).FirstOrDefault() != designation.Code && designation.Code != null)
            {
                if (_db.Designation.Where(i => i.Code == designation.Code).ToList().Count < 1)
                {
                    string userName = User.Identity.Name;
                    int userId = DbUtility.GetUserId(_db, userName);
                    designation.UpdatedBy = userId;
                    designation.UpdateDate = Utility.Utility.GetCurrentDateTime();
                    designation.DepartmentId = Convert.ToInt32(Request["ddl_dept"]);
                    _db.Entry(designation).State = EntityState.Modified;
                    _db.SaveChanges();
                    TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.UpdateSuccess);
                }
                else
                {
                    TempData["message"] =  DbUtility.GetStatusMessage(DbUtility.Status.Exist);
                }
            }
            else
            {
                string userName = User.Identity.Name;
                int userId = DbUtility.GetUserId(_db, userName);
                designation.UpdatedBy = userId;
                designation.UpdateDate = Utility.Utility.GetCurrentDateTime();
                designation.DepartmentId = Convert.ToInt32(Request["ddl_dept"]);
                _db.Entry(designation).State = EntityState.Modified;
                _db.SaveChanges();
                TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.UpdateSuccess);
            }
            int departmentId = designation.DepartmentId;
            ViewBag.DepartmentId = _db.Department.Where(x => x.Sl == departmentId).Select(t => t.Sl).FirstOrDefault();
            ViewBag.DepartmentName = _db.Department.Where(x => x.Sl == departmentId).Select(t => t.Name).FirstOrDefault();
            int departmentGroupId = _db.Department.Where(x => x.Sl == departmentId).Select(t => t.DepartmentGroupId).FirstOrDefault();
            ViewBag.DepartmentGroupId = new SelectList(departmentGroupList, "Sl", "Name", departmentGroupId);
            ViewBag.RoleName = new SelectList(roleList, "Name", "Name", designation.RoleName);
            return View(designation);
        }
        #endregion

        #region Delete
        // GET: Designations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Designation designation = _db.Designation.Find(id);
            if (designation == null)
            {
                return HttpNotFound();
            }
            return View(designation);
        }

        // POST: Designations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (_db.Employee.Where(i => i.DesignationId == id && i.Status == true).ToList().Count < 1)
            {

FTL_HRMS/Views/Designations/Create.cshtml
@model FTL_HRMS.Models.Hr.Designation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Designation</h1>
        </div>
    </div>
</div>

<header class="panel_header">
    <h2 class="title pull-left">Add New Designation</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>
<div class="content-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    @Html.Partial("~/Views/Shared/WarningMessage.cshtml")
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Status)
                    @Html.HiddenFor(model => model.CreateDate)
                    @Html.HiddenFor(model => model.CreatedBy)
                    @Html.HiddenFor(model => model.UpdateDate)
                    @Html.HiddenFor(model => model.UpdatedBy)
                    <div class="col-md-offset-3">
                        <div class="btn-group col-md-offset-5">
                            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "Designations" )'">Back To List</button>
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Code)
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", style = "width:50%" } })
                            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.Name, new { @class = "required" })
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "width:50%", @required=true } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.Label("Department Group", new { @class = "required" })
                        </div>
                        <div>
                            @Html.DropDownList("DepartmentGroupId", null, "Select Group", htmlAttributes: new { @class = "form-control", style = "width:50%", @id = "ddl_deptgroup", @name = "ddl_deptgroup", @onchange = "LoadDepartment();", @required = true })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.DepartmentId, "Department", new { @class = "required" })
                        </div>
                        <div>
                            <select class="form-control" style="width:50%" id="ddl_dept" name="ddl_dept" required>
                                <option value="">Select Department</option>
                            </select>
                        </div>

                        <div>
                            @Html.LabelFor(model => model.RoleName, "Role Name", new { @class = "required" })
                        </div>
                        <div>
                            @Html.DropDownList("RoleName", null, "Select Role", htmlAttributes: new { @class = "form-control", style = "width:50%", @required=true })
                        </div>
                                               
                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-9" style="margin-left:180px;">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script>
    function LoadDepartment() {
        $.ajax({
            url: '/Departments/GetDepartmentByGroupId',
            method: 'POST',
            data: {
                DepartmentGroupId: $('#ddl_deptgroup').val(),
            },
            cache: false,
            error: function () {
                alert("An error occoured!");
            },
            success: function (response) {
                $('#ddl_dept').empty();
                $('#ddl_dept').append($('<option>', {
                    value: '',
                    text: 'Select Department'
                }));
                for (var i = 0; i < response.length; i++) {
                    var opt = new Option(response[i].Name, response[i].Sl);
                    $('#ddl_dept').append(opt);
                }
            }
        });
    };
</script>

FTL_HRMS/Views/Designations/Delete.cshtml
@model FTL_HRMS.Models.Hr.Designation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Designation</h1>
        </div>
    </div>
</div>
<header class="panel_header">
    <h2 class="title pull-left">Delete Designation</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="col-md-offset-4">
    <h3>Are you sure you want to delete this?</h3>
    <br />
</div>
<div class="col-md-offset-4">
    <dl class="dl-horizontal">
        <dt>
            Code
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Department Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            Created By
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateEmployee.Name)
        </dd>

        <dt>
            Create Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            Updated By
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateEmployee.Name)
        </dd>

        <dt>
            Update Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="btn-group" style="margin-left:10%">
            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "Designations")'">Back To List</button>
        </div>
        <div class="btn-group" style="margin-left:5%">
            <input type="submit" class="btn btn-danger btn-sm" aria-expanded="false" value="Delete" />
        </div>
    }
</div>
<br />

FTL_HRMS/Views/Designations/Details.cshtml
@model FTL_HRMS.Models.Hr.Designation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Designation</h1>
        </div>
    </div>
</div>
<header class="panel_header">
    <h2 class="title pull-left">Designation Details</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="col-md-offset-4">
    <br />
    <dl class="dl-horizontal">
                <dt>
                    Code
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Code)
                </dd>

                <dt>
                    Name
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    Department Name
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Department.Name)
                </dd>

                <dt>
                    Role Name
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.RoleName)
                </dd>

                <dt>
                    Created By
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreateEmployee.Name)
                </dd>

                <dt>
                    Create Date
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreateDate)
                </dd>

                <dt>
                    Updated By
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateEmployee.Name)
                </dd>

                <dt>
                    Update Date
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateDate)
                </dd>

            </dl>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="btn-group" style="margin-left:10%">
                    <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "Designations")'">Back To List</button>
                </div>
                <div class="btn-group" style="margin-left:5%">
                    <button type="button" class="btn btn-warning btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Edit", "Designations", new { id = Model.Sl })'">Edit</button>
                </div>
            }
            <br />
        </div>

FTL_HRMS/Views/Designations/Edit.cshtml
@model FTL_HRMS.Models.Hr.Designation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Designation</h1>
        </div>
    </div>
</div>

<header class="panel_header">
    <h2 class="title pull-left">Add New Designation</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>
<div class="content-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    @Html.Partial("~/Views/Shared/WarningMessage.cshtml")
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Sl)
                    @Html.HiddenFor(model => model.Status)
                    @Html.HiddenFor(model => model.CreateDate)
                    @Html.HiddenFor(model => model.CreatedBy)
                    @Html.HiddenFor(model => model.UpdateDate)
                    @Html.HiddenFor(model => model.UpdatedBy)
                    <div class="col-md-offset-3">
                        <div class="btn-group col-md-offset-5">
                            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "Designations" )'">Back To List</button>
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Code)
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", style = "width:50%" } })
                            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.Name, new { @class = "required" })
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", style = "width:50%", @required=true } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>


                        <div>
                            @Html.Label("Department Group", new { @class = "required" })
                        </div>
                        <div>
                            @Html.DropDownList("DepartmentGroupId", null, "Select Group", htmlAttributes: new { @class = "form-control", style = "width:50%", @id = "ddl_deptgroup", @name = "ddl_deptgroup", @onchange = "LoadDepartment();", @required = true })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.DepartmentId, "Department", new { @class = "required" })
                        </div>
                        <div>
                            <select class="form-control" style="width:50%" id="ddl_dept" name="ddl_dept" required>
                                <option value="">Select Department</option>
                                <option value=@ViewBag.DepartmentId selected>@ViewBag.DepartmentName</option>
                            </select>
                        </div>

                        <div>
                            @Html.LabelFor(model => model.RoleName, "Role Name", new { @class = "required" })
                        </div>
                        <div>
                            @Html.DropDownList("RoleName", null, "Select Role", htmlAttributes: new { @class = "form-control", style = "width:50%", @required = true })
                        </div>
                       


                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-9" style="margin-left:180px;">
                                <input type="submit" value="Update" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script>
    function LoadDepartment() {
        $.ajax({
            url: '/Departments/GetDepartmentByGroupId',
            method: 'POST',
            data: {
                DepartmentGroupId: $('#ddl_deptgroup').val(),
            },
            cache: false,
            error: function () {
                alert("An error occoured!");
            },
            success: function (response) {
                $('#ddl_dept').empty();
                $('#ddl_dept').append($('<option>', {
                    value: '',
                    text: 'Select Department'
                }));
                for (var i = 0; i < response.length; i++) {
                    var opt = new Option(response[i].Name, response[i].Sl);
                    $('#ddl_dept').append(opt);
                }
            }
        });
    };
</script>