FTL_HRMS/Models/Payroll/Holiday.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FTL_HRMS.Models.Payroll
{
    [Table("tbl_Holiday")]
    public class Holiday
    {
        [Key]
        public int Sl { get; set; }

        [DataType(DataType.Date),
        DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}",
        ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Remarks cannot be empty")]
        public string Remarks { get; set; }
    }
}

FTL_HRMS/Controllers/HolidaysController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FTL_HRMS.DAL;
using FTL_HRMS.Models.Payroll;
using FTL_HRMS.Utility;

namespace FTL_HRMS.Controllers
{
    public class HolidaysController : Controller
    {
        private HRMSDbContext _db = new HRMSDbContext();

        #region List
        // GET: Holidays
        public ActionResult Index()
        {
            return View(_db.Holiday.ToList());
        }
        #endregion

        #region Details
        // GET: Holidays/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Holiday holiday = _db.Holiday.Find(id);
            if (holiday == null)
            {
                return HttpNotFound();
            }
            return View(holiday);
        }
        #endregion

        #region Create
        // GET: Holidays/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Holidays/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,Date,Remarks")] Holiday holiday)
        {
            if (holiday.Date != null)
            {
                _db.Holiday.Add(holiday);
                _db.SaveChanges();
                TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.AddSuccess);
                return RedirectToAction("Create");
            }
            TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.AddFailed);
            return View(holiday);
        }
        #endregion

        #region Edit
        // GET: Holidays/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Holiday holiday = _db.Holiday.Find(id);
            if (holiday == null)
            {
                return HttpNotFound();
            }
            return View(holiday);
        }

        // POST: Holidays/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,Date,Remarks")] Holiday holiday)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(holiday).State = EntityState.Modified;
                _db.SaveChanges();
                TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.UpdateSuccess);
                return View(holiday);
            }
            TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.UpdateFailed);
            return View(holiday);
        }
        #endregion

        #region Delete
        // GET: Holidays/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Holiday holiday = _db.Holiday.Find(id);
            if (holiday == null)
            {
                return HttpNotFound();
            }
            return View(holiday);
        }

        // POST: Holidays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Holiday holiday = _db.Holiday.Find(id);
            _db.Holiday.Remove(holiday);
            _db.SaveChanges();
            TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.DeleteSuccess);
            return RedirectToAction("Index");
        }
        #endregion

        #region Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

FTL_HRMS/Views/Holidays/Create.cshtml
@model FTL_HRMS.Models.Payroll.Holiday

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Holiday</h1>
        </div>
    </div>
</div>

<header class="panel_header">
    <h2 class="title pull-left">Add New Holiday</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="content-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    @Html.Partial("~/Views/Shared/WarningMessage.cshtml")
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-md-offset-3">
                        <div class="btn-group col-md-offset-5">
                            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "Holidays" )'">Back To List</button>
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Date, new { @class = "required" })
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new {@type="text", @placeholder="mm/dd/yyyy", @class = "form-control datepicker", style = "width:50%", @required = true } })
                            @Html.ValidationMessageFor(model => model.Date , "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.Remarks, new { @class = "required" })
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control", style = "width:50%", @required = true } })
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>
                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-9" style="margin-left:180px;">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

FTL_HRMS/Views/Holidays/Delete.cshtml
@model FTL_HRMS.Models.Payroll.Holiday

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Holiday</h1>
        </div>
    </div>
</div>
<header class="panel_header">
    <h2 class="title pull-left">Delete Holiday</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="col-md-offset-4">
    <h3>Are you sure you want to delete this?</h3>
    <br />
</div>
<div class="col-md-offset-4">
    <dl class="dl-horizontal">
        <dt>
            Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            Remarks
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="btn-group" style="margin-left:10%">
            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "Holidays")'">Back To List</button>
        </div>
        <div class="btn-group" style="margin-left:5%">
            <input type="submit" class="btn btn-danger btn-sm" aria-expanded="false" value="Delete" />
        </div>
    }
</div>
<br />

FTL_HRMS/Views/Holidays/Details.cshtml
@model FTL_HRMS.Models.Payroll.Holiday

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Holiday</h1>
        </div>
    </div>
</div>
<header class="panel_header">
    <h2 class="title pull-left">Holiday Details</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="col-md-offset-4">
    <br />
    <dl class="dl-horizontal">
        <dt>
            Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            Remarks
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="btn-group" style="margin-left:10%">
            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "Holidays")'">Back To List</button>
        </div>
        <div class="btn-group" style="margin-left:5%">
            <button type="button" class="btn btn-warning btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Edit", "Holidays", new { id = Model.Sl })'">Edit</button>
        </div>
    }
    <br />
</div>

FTL_HRMS/Views/Holidays/Edit.cshtml
@model FTL_HRMS.Models.Payroll.Holiday

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Holiday</h1>
        </div>
    </div>
</div>

<header class="panel_header">
    <h2 class="title pull-left">Edit Holiday</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="content-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    @Html.Partial("~/Views/Shared/WarningMessage.cshtml")
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Sl)
                    <div class="col-md-offset-3">
                        <div class="btn-group col-md-offset-5">
                            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "Holidays" )'">Back To List</button>
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Date, new { @class = "required" })
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker", @type = "DateTime", style = "width:50%", @required = true } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.Remarks, new { @class = "required" })
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control", style = "width:50%", @required = true } })
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>
                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-9" style="margin-left:180px;">
                                <input type="submit" value="Update" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

FTL_HRMS/Views/Holidays/Index.cshtml
@model IEnumerable<FTL_HRMS.Models.Payroll.Holiday>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous">
</script>
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Holiday</h1>
        </div>
    </div>
</div>
<header class="panel_header">
    <h2 class="title pull-left">Holidays List</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="content-body">
    <div class="row">
        @Html.Partial("~/Views/Shared/WarningMessage.cshtml")
        <div class="col-md-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Create", "Holidays")'">Add Holiday</button>
            </div>
        </div>
        <div class="col-md-6 text-right">
            <div class="btn-group">
                <button type="button" onclick="location.href='@Url.Action("PrintHolidayReport", "Reports")'" target="_blank" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-print"></span> Download PDF
                </button>
            </div>
        </div>
    <br /><br />
        <div class="col-md-12 col-sm-12 col-xs-12">
            @{int rowNo = 0;}
            <table id="myTable" class="table table-striped dt-responsive display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Action</th>
                        <th>
                            @Html.DisplayNameFor(model => model.Date)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Remarks)
                        </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>SL</th>
                        <th>Action</th>
                        <th>
                            @Html.DisplayNameFor(model => model.Date)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Remarks)
                        </th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td align="center" width="5%">
                                @(rowNo += 1)
                            </td>
                            <td align="center" width="6%">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" aria-expanded="false">Options <span class="caret"></span></button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>@Html.ActionLink("Edit", "Edit", new { id = item.Sl })</li>
                                        <li>@Html.ActionLink("Details", "Details", new { id = item.Sl })</li>
                                        <li>@Html.ActionLink("Delete", "Delete", new { id = item.Sl })</li>
                                    </ul>
                                </div>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Remarks)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
$(document).ready(function(){
    $('#myTable').DataTable();
});
</script>