FTL_HRMS/Models/Hr/DisciplinaryActionType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FTL_HRMS.Models.Hr
{
    [Table("tbl_DisciplinaryActionType")]
    public class DisciplinaryActionType
    {
        [Key]
        public int Sl { get; set; }
        
        [Required(ErrorMessage = "Name cannot be empty")]
        [MaxLength(250)]
        public string Name { get; set; }
    }
}

FTL_HRMS/Controllers/DisciplinaryActionsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FTL_HRMS.DAL;
using FTL_HRMS.Models.Hr;
using FTL_HRMS.Utility;

namespace FTL_HRMS.Controllers
{
    public class DisciplinaryActionsController : Controller
    {
        private HRMSDbContext _db = new HRMSDbContext();

        #region List
        // GET: DisciplinaryActions
        public ActionResult Index()
        {
            string userName = User.Identity.Name;
            int userId = DbUtility.GetUserId(_db, userName);
            List<DisciplinaryAction> disciplinaryActionList = _db.DisciplinaryAction.Include(i => i.DisciplinaryActionType).Include(i => i.Employee).Where(i => i.EmployeeId != userId).ToList();
            return View(disciplinaryActionList);
        }
        #endregion

        #region Details (We don't use it)
        // GET: DisciplinaryActions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DisciplinaryAction disciplinaryAction = _db.DisciplinaryAction.Find(id);
            if (disciplinaryAction == null)
            {
                return HttpNotFound();
            }
            return View(disciplinaryAction);
        }
        #endregion

        #region Create
        // GET: DisciplinaryActions/Create
        public ActionResult Create()
        {
            ViewBag.DisciplinaryActionTypeId = new SelectList(_db.DisciplinaryActionType, "Sl", "Name");
            return View();
        }

        // POST: DisciplinaryActions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,EmployeeId,DisciplinaryActionTypeId,Date,Remarks")] DisciplinaryAction disciplinaryAction)
        {
            if (ModelState.IsValid)
            {
                _db.DisciplinaryAction.Add(disciplinaryAction);
                _db.SaveChanges();
                TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.AddSuccess);
                ViewBag.DisciplinaryActionTypeId = new SelectList(_db.DisciplinaryActionType, "Sl", "Name");
                return RedirectToAction("Create");
            }
            ViewBag.DisciplinaryActionTypeId = new SelectList(_db.DisciplinaryActionType, "Sl", "Name", disciplinaryAction.DisciplinaryActionTypeId);
            TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.AddFailed);
            return View(disciplinaryAction);
        }
        #endregion

        #region Edit
        // GET: DisciplinaryActions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DisciplinaryAction disciplinaryAction = _db.DisciplinaryAction.Find(id);
            if (disciplinaryAction == null)
            {
                return HttpNotFound();
            }
            ViewBag.DisciplinaryActionTypeId = new SelectList(_db.DisciplinaryActionType, "Sl", "Name", disciplinaryAction.DisciplinaryActionTypeId);
            return View(disciplinaryAction);
        }

        // POST: DisciplinaryActions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,EmployeeId,DisciplinaryActionTypeId,Date,Remarks")] DisciplinaryAction disciplinaryAction)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(disciplinaryAction).State = EntityState.Modified;
                _db.SaveChanges();
                TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.UpdateSuccess);
                ViewBag.DisciplinaryActionTypeId = new SelectList(_db.DisciplinaryActionType, "Sl", "Name");
                return RedirectToAction("Create");
            }
            ViewBag.DisciplinaryActionTypeId = new SelectList(_db.DisciplinaryActionType, "Sl", "Name", disciplinaryAction.DisciplinaryActionTypeId);
            TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.UpdateFailed);
            return View(disciplinaryAction);
        }
        #endregion

        #region Delete
        // GET: DisciplinaryActions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DisciplinaryAction disciplinaryAction = _db.DisciplinaryAction.Find(id);
            if (disciplinaryAction == null)
            {
                return HttpNotFound();
            }
            return View(disciplinaryAction);
        }

        // POST: DisciplinaryActions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DisciplinaryAction disciplinaryAction = _db.DisciplinaryAction.Find(id);
            _db.DisciplinaryAction.Remove(disciplinaryAction);
            _db.SaveChanges();
            TempData["message"] = DbUtility.GetStatusMessage(DbUtility.Status.DeleteSuccess);
            return RedirectToAction("Index");
        }
        #endregion

        #region Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

FTL_HRMS/Views/DisciplinaryActions/Create.cshtml
@model FTL_HRMS.Models.Hr.DisciplinaryAction

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@section scripts {
    <script src="~/Scripts/myScript.js" type="text/javascript"></script>
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Disciplinary Actions</h1>
        </div>
    </div>
</div>

<header class="panel_header">
    <h2 class="title pull-left">Add Disciplinary Actions</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="content-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    @Html.Partial("~/Views/Shared/WarningMessage.cshtml")
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-md-offset-3">
                        <div class="btn-group col-md-offset-5">
                            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "DisciplinaryActions" )'">Back To List</button>
                        </div>
                        <div>
                            @Html.LabelFor(model => model.EmployeeId, "Employee Code Or Name", new { @class = "required" })
                        </div>
                        <div>
                            <input type="hidden" id="EmployeeId" name="EmployeeId" />
                            <input type="text" id="EmployeeCode" value="" placeholder="Select Existing Employee" class="form-control" style="width:50%" required />
                            @*@Html.DropDownList("EmployeeId", null, "--Select Employee--", htmlAttributes: new { @class = "form-control", style = "width:50%", @required = true })
                            @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })*@
                        </div>

                        <div>
                            @Html.LabelFor(model => model.DisciplinaryActionTypeId, "Disciplinary Action Type", new { @class = "required" })
                        </div>
                        <div>
                            @Html.DropDownList("DisciplinaryActionTypeId", null, "--Select Type--", htmlAttributes: new { @class = "form-control", style = "width:50%", @required = true })
                            @Html.ValidationMessageFor(model => model.DisciplinaryActionTypeId, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.Date, new { @class = "required" })
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @type = "text", @placeholder="mm/dd/yyyy", @class = "form-control datepicker", style = "width:50%", @required = true } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.Remarks)
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control", style = "width:50%" } })
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>


                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-9" style="margin-left:180px;">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

FTL_HRMS/Views/DisciplinaryActions/Delete.cshtml
@model FTL_HRMS.Models.Hr.DisciplinaryAction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DisciplinaryAction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisciplinaryActionTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisciplinaryActionTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FTL_HRMS/Views/DisciplinaryActions/Details.cshtml
@model FTL_HRMS.Models.Hr.DisciplinaryAction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DisciplinaryAction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisciplinaryActionTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisciplinaryActionTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Sl }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FTL_HRMS/Views/DisciplinaryActions/Edit.cshtml
@model FTL_HRMS.Models.Hr.DisciplinaryAction

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Disciplinary Actions</h1>
        </div>
    </div>
</div>

<header class="panel_header">
    <h2 class="title pull-left">Edit Disciplinary Actions</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="content-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    @Html.Partial("~/Views/Shared/WarningMessage.cshtml")
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Sl)
                    @Html.HiddenFor(model => model.EmployeeId)
                    <div class="col-md-offset-3">
                        <div class="btn-group col-md-offset-5">
                            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Index", "DisciplinaryActions" )'">Back To List</button>
                        </div>

                        <div>
                            @Html.LabelFor(model => model.DisciplinaryActionTypeId, "Disciplinary Action Type", new { @class = "required" })
                        </div>
                        <div>
                            @Html.DropDownList("DisciplinaryActionTypeId", null, "--Select Type--", htmlAttributes: new { @class = "form-control", style = "width:50%", @required = true })
                            @Html.ValidationMessageFor(model => model.DisciplinaryActionTypeId, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.Date, new { @class = "required" })
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker", @type = "DateTime", style = "width:50%", @required = true } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.Remarks)
                        </div>
                        <div>
                            @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control", style = "width:50%" } })
                            @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                        </div>


                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-9" style="margin-left:180px;">
                                <input type="submit" value="Update" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

FTL_HRMS/Views/DisciplinaryActions/Index.cshtml
@model IEnumerable<FTL_HRMS.Models.Hr.DisciplinaryAction>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous">
</script>
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Disciplinary Action</h1>
        </div>
    </div>
</div>
<header class="panel_header">
    <h2 class="title pull-left">Disciplinary Action List</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>

<div class="content-body">
    <div class="row">
        @Html.Partial("~/Views/Shared/WarningMessage.cshtml")
        <div class="col-md-6">
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Create", "DisciplinaryActions")'">Add Disciplinary Action</button>
            </div>
        </div>
        <div class="col-md-6 text-right">
            <div class="btn-group">
                <button type="button" onclick="location.href='@Url.Action("PrintDisciplinaryActionHistoryReport", "Reports")'" target="_blank" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-print"></span> Download PDF
                </button>
            </div>
        </div>
        <br /><br />
        <div class="col-md-12 col-sm-12 col-xs-12">
            @{int rowNo = 0;}
            <table id="myTable" class="table table-striped dt-responsive display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Action</th>
                        <th>
                            Employee Code
                        </th>
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Type Name
                        </th>
                        <th>
                            Date
                        </th>
                        <th>
                            Remarks
                        </th>

                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>SL</th>
                        <th>Action</th>
                        <th>
                            Employee Code
                        </th>
                        <th>
                            Employee Name
                        </th>
                        <th>
                            Type Name
                        </th>
                        <th>
                            Date
                        </th>
                        <th>
                            Remarks
                        </th>

                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td align="center" width="5%">
                                @(rowNo += 1)
                            </td>
                            <td align="center" width="5%">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Edit", "DisciplinaryActions", new { id = item.Sl })'">Edit</button>
                                </div>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Employee.Code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Employee.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DisciplinaryActionType.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Remarks)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
$(document).ready(function(){
    $('#myTable').DataTable();
});
</script>