FTL_HRMS/Models/Payroll/MonthlyAttendance.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FTL_HRMS.Models.Hr;
using System.ComponentModel;

namespace FTL_HRMS.Models.Payroll
{
    [Table("tbl_MonthlyAttendance")]
    public class MonthlyAttendance
    {       
        [Key]
        public int Sl { get; set; }

        [Required(ErrorMessage = "Employee cannot be empty")]
        [ForeignKey("Employee")]
        public int EmployeeId { get; set; }

        [DataType(DataType.Date),
        DisplayFormat(DataFormatString = "{0:dd-MM-yy}",
        ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Status cannot be empty")]
        public string Status { get; set; }

        [ForeignKey("UpdateEmployee")]
        public int? UpdatedBy { get; set; }

        [DataType(DataType.Date),
        DisplayFormat(DataFormatString = "{0:dd-MM-yy}",
        ApplyFormatInEditMode = true)]
        public DateTime? UpdateDate { get; set; }

        [DefaultValue(false)]
        public bool IsCalculated { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Employee UpdateEmployee { get; set; }
    }
}

FTL_HRMS/Controllers/MonthlyAttendancesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FTL_HRMS.DAL;
using FTL_HRMS.Models.Payroll;
using FTL_HRMS.Models.ViewModels;
using FTL_HRMS.Utility;
using FTL_HRMS.Models.Hr;

namespace FTL_HRMS.Controllers
{
    public class MonthlyAttendancesController : Controller
    {
        private HRMSDbContext _db = new HRMSDbContext();
        //AttendanceController _att = new AttendanceController();

        // GET: MonthlyAttendances
        public ActionResult Index()
        {
            var monthlyAttendance = _db.MonthlyAttendance.Include(m => m.Employee);
            return View(monthlyAttendance.ToList());
        }

        #region Employee Attendence Report
        public ActionResult EmployeeAttendenceReport()
        {
            //_att.SyncAttendance();
            List<DepartmentGroup> groupList = new List<DepartmentGroup>();
            groupList = _db.DepartmentGroup.Where(i => i.Status == true).ToList();
            ViewBag.DepartmentGroupId = new SelectList(groupList, "Sl", "Name");
            List<MonthlyAttendance> attendenceList = GetEmployeeList(0, 0, Utility.Utility.GetDefaultDate());
            return View(attendenceList);
        }

        [HttpPost]
        public ActionResult EmployeeAttendenceReport(string departmentGroupId, string ddlDept)
        {
            int dgid, did;
            Int32.TryParse(departmentGroupId, out dgid);
            Int32.TryParse(ddlDept, out did);
            DateTime date = Utility.Utility.GetDefaultDate();
            DateTime.TryParse(Request["Date"], out date);

            List<DepartmentGroup> groupList = new List<DepartmentGroup>();
            groupList = _db.DepartmentGroup.Where(i => i.Status == true).ToList();
            ViewBag.DepartmentGroupId = new SelectList(groupList, "Sl", "Name");

            ViewBag.Status = "SelectType";
            TempData["dgid"] = dgid;
            TempData["did"] = did;
            TempData["Date"] = date;
            List<MonthlyAttendance> attendenceList = GetEmployeeList(dgid, did, date);
            return View(attendenceList);
        }
        public List<MonthlyAttendance> GetEmployeeList(int departmentGroupId, int departmentId, DateTime date)
        {
            List<MonthlyAttendance> attendenceList = new List<MonthlyAttendance>();
            if (date.Equals(Utility.Utility.GetDefaultDate()))
            {
                date = Utility.Utility.GetCurrentDateTime().AddDays(-1);
            }
            if (departmentGroupId > 0)
            {
                if (departmentId > 0)
                {
                    attendenceList = _db.MonthlyAttendance.Where(x => x.Employee.Designation.Department.DepartmentGroup.Sl.Equals(departmentGroupId)).Where(x => x.Employee.Designation.Department.Sl.Equals(departmentId)).Where(x=> x.Date==date).ToList();
                }
                else
                {
                    attendenceList = _db.MonthlyAttendance.Where(x => x.Employee.Designation.Department.DepartmentGroup.Sl.Equals(departmentGroupId)).Where(x => x.Date == date).ToList();
                    
                }

            }
            else if (departmentGroupId == 0)
            {
                attendenceList = _db.MonthlyAttendance.Include(x => x.Employee).Where(x=>x.Date == date).ToList();
            }
            else
            {
                attendenceList = _db.MonthlyAttendance.Include(x=> x.Employee).ToList();
            }
            return attendenceList;
        }
        #endregion

        #region EmployeeWise Attendence
        public ActionResult EmployeewiseAttendenceReport()
        {
            //_att.SyncAttendance();
            string userName = User.Identity.Name;
            int userId = DbUtility.GetUserId(_db, userName);
            List<Employee> employeeList = new List<Employee>();
            employeeList = _db.Employee.Where(i => i.Status == true && i.IsSystemOrSuperAdmin == false && i.Sl != userId).ToList();
            ViewBag.EmployeeId = new SelectList(employeeList, "Sl", "Code");
            List<MonthlyAttendance> attendenceList = GetEmployeewiseList(0, Utility.Utility.GetDefaultDate(), Utility.Utility.GetDefaultDate());
            return View(attendenceList);
        }
        [HttpPost]
        public ActionResult EmployeewiseAttendenceReport(string employeeId)
        {
            int eid;
            Int32.TryParse(employeeId, out eid);
            DateTime fromDate = Utility.Utility.GetDefaultDate();
            if(Request["FromDate"]!="")
            {
                DateTime.TryParse(Request["FromDate"], out fromDate);
            }
            DateTime toDate = Utility.Utility.GetDefaultDate();
            if (Request["ToDate"]!="")
            {
                DateTime.TryParse(Request["ToDate"], out toDate);
            }
            string userName = User.Identity.Name;
            int userId = DbUtility.GetUserId(_db, userName);
            List<Employee> employeeList = new List<Employee>();
            employeeList = _db.Employee.Where(i => i.Status == true && i.IsSystemOrSuperAdmin == false && i.Sl != userId).ToList();
            ViewBag.EmployeeId = new SelectList(employeeList, "Sl", "Code");
            ViewBag.Status = "SelectType";
            TempData["dgid"] = eid;
            TempData["FromDate"] = fromDate;
            TempData["ToDate"] = toDate;
            ViewBag.FromDate = fromDate;
            ViewBag.ToDate = toDate;
            ViewBag.EmpId = Int32.TryParse(employeeId, out eid);
            List<MonthlyAttendance> attendenceList = GetEmployeewiseList(eid, fromDate, toDate);
            return View(attendenceList);
        }

        public List<MonthlyAttendance> GetEmployeewiseList(int employeeId, DateTime fromDate, DateTime toDate)
        {
            List<MonthlyAttendance> attendenceList = new List<MonthlyAttendance>();
            if (fromDate.Equals(Utility.Utility.GetDefaultDate()))
            {
                fromDate = Utility.Utility.GetCurrentDateTime().AddDays(-1);
                toDate = Utility.Utility.GetCurrentDateTime().AddDays(-1);
            }
            if (toDate.Equals(Utility.Utility.GetDefaultDate()))
            {
                toDate = Utility.Utility.GetCurrentDateTime().AddDays(-1);
            }
            if (employeeId > 0 && Request["ToDate"] != "" && Request["FromDate"] != "" || 
                employeeId > 0 && Request["ToDate"] == "" && Request["FromDate"] != "" ||
                employeeId > 0 && Request["ToDate"] != "" && Request["FromDate"] == "")
            {
                attendenceList = _db.MonthlyAttendance.Where(x => x.Employee.Sl.Equals(employeeId)).Where(x => x.Date >= fromDate  && x.Date <= toDate).ToList();
            }
            else if (employeeId > 0 && Request["ToDate"] == "" && Request["FromDate"] == "")
            {
                attendenceList = _db.MonthlyAttendance.Where(x => x.Employee.Sl.Equals(employeeId)).Where(x => x.Date.Day == toDate.Day && x.Date.Month == toDate.Month && x.Date.Year == toDate.Year).ToList();
            }
            else 
            {
                attendenceList = _db.MonthlyAttendance.Where(x => DbFunctions.TruncateTime(x.Date) >= fromDate.Date && DbFunctions.TruncateTime(x.Date) <= toDate.Date).ToList();
            }
            ViewBag.FromDate = fromDate;
            ViewBag.ToDate = toDate;
            ViewBag.EmpId = employeeId;
            return attendenceList;
        }

        #endregion


        #region EmployeeWise Attendence
        public ActionResult EmployeewiseFilterAttendenceReport()
        {
            //_att.SyncAttendance();
            List<Employee> employeeList = new List<Employee>();
            employeeList = _db.Employee.Where(i => i.Status == true && i.IsSystemOrSuperAdmin == false).ToList();
            ViewBag.EmployeeId = new SelectList(employeeList, "Sl", "Code");
            List<FilterAttendanceView> attendenceList = GetEmployeewiseFilterList(0, Utility.Utility.GetDefaultDate(), Utility.Utility.GetDefaultDate());
            return View(attendenceList);
        }
        [HttpPost]
        public ActionResult EmployeewiseFilterAttendenceReport(string employeeId)
        {
            int eid;
            Int32.TryParse(employeeId, out eid);
            DateTime fromDate = Utility.Utility.GetDefaultDate();
            if (Request["FromDate"] != "")
            {
                DateTime.TryParse(Request["FromDate"], out fromDate);
            }
            DateTime toDate = Utility.Utility.GetDefaultDate();
            if (Request["ToDate"] != "")
            {
                DateTime.TryParse(Request["ToDate"], out toDate);
            }
            var employeeList = _db.Employee.Where(i => i.Status == true && i.IsSystemOrSuperAdmin == false).ToList();
            ViewBag.EmployeeId = new SelectList(employeeList, "Sl", "Code");
            ViewBag.Status = "SelectType";
            TempData["dgid"] = eid;
            TempData["FromDate"] = fromDate;
            TempData["ToDate"] = toDate;
            ViewBag.FromDate = fromDate;
            ViewBag.ToDate = toDate;
            ViewBag.EmpId = Int32.TryParse(employeeId, out eid);
            List<FilterAttendanceView> attendenceList = GetEmployeewiseFilterList(eid, fromDate, toDate);
            return View(attendenceList);
        }

        public List<FilterAttendanceView> GetEmployeewiseFilterList(int employeeId, DateTime fromDate, DateTime toDate)
        {
            string query;
            if (fromDate.Equals(Utility.Utility.GetDefaultDate()))
            {
                fromDate = Utility.Utility.GetCurrentDateTime().AddDays(-1);
                toDate = Utility.Utility.GetCurrentDateTime().AddDays(-1);
            }
            if (toDate.Equals(Utility.Utility.GetDefaultDate()))
            {
                toDate = Utility.Utility.GetCurrentDateTime().AddDays(-1);
            }

FTL_HRMS/Views/MonthlyAttendances/Create.cshtml
@model FTL_HRMS.Models.Payroll.MonthlyAttendance

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MonthlyAttendance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCalculated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCalculated)
                    @Html.ValidationMessageFor(model => model.IsCalculated, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FTL_HRMS/Views/MonthlyAttendances/Delete.cshtml
@model FTL_HRMS.Models.Payroll.MonthlyAttendance

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MonthlyAttendance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCalculated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCalculated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FTL_HRMS/Views/MonthlyAttendances/Details.cshtml
@model FTL_HRMS.Models.Payroll.MonthlyAttendance

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MonthlyAttendance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCalculated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCalculated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Sl }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FTL_HRMS/Views/MonthlyAttendances/EmployeeAttendenceReport.cshtml
@model IEnumerable<FTL_HRMS.Models.Payroll.MonthlyAttendance>

@{
    ViewBag.Title = "Employee List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous">
</script>
@using (Html.BeginForm())
{
    <header class="panel_header">
        <h2 class="title pull-left">Selection</h2>
        <div class="actions panel_actions pull-right">
            <i class="box_toggle fa fa-chevron-down"></i>
        </div>
    </header>
    <br /> <br />
    <div class="content-body">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="form-group">
                    <div class="col-md-4">
                        <div><label class="form-label"> Select Department Group:</label></div>
                        <div>@Html.DropDownList("DepartmentGroupId", null, "--All--", htmlAttributes: new { @class = "form-control", style = "width:100%", @id = "ddl_deptgroup", @name = "ddl_deptgroup", @onchange = "LoadDepartment();" })</div>
                    </div>
                    <div class="col-md-4">
                        <div><label class="form-label">  Select Department:</label></div>
                        <div>
                            <select class="form-control"  id="ddl_dept" name="ddl_dept" tabindex=20>
                                <option value="">--All--</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-label" for="date">Date</label>
                            <div>
                                <input type="text" id="date" name="Date" class="form-control datepicker" data-start-view="2" placeholder="mm/dd/yyyy" >
                            </div>
                        </div>
                    </div>
                   </div>
                </div>
            <div class="col-md-offset-2" style="margin-left:45%">
                <input type="submit" value="Submit" name="Submit" class="btn btn-info" />
            </div>
            </div>
        </div>
}
<header class="panel_header">
    <h2 class="title pull-left">List Of Employee</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>
<br /> <br />
<div class="content-body">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @{int rowNo = 0;}
            <table id="myTable" class="table table-striped dt-responsive display" cellspacing="0" width="100%">

                <thead>
                    <tr>
                        <th style="text-align:center">SL</th>
                        <th data-priority="1" style="text-align:center">Code</th>
                        <th data-priority="1" style="text-align:center">Name</th>
                        <th data-priority="3" style="text-align:center">Phone</th>
                        <th data-priority="1" style="text-align:center">Designation</th>
                        <th data-priority="6" style="text-align:center">Status</th>
                        <th style="text-align:center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td align="center" width="5%">
                                @(rowNo += 1)
                            </td>

                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Employee.Code)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Employee.Name)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Employee.Mobile)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Employee.Designation.Name)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>

                            <td align="center" width="8%">
                                @if (item.Status == "A")
                                {
                                    <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Edit", "MonthlyAttendances", new { id = item.Sl })'">Present</button>
                                }
                            </td>

                        </tr>
                    }

                </tbody>

            </table>

        </div>
    </div>
</div>


<script>
    function LoadDepartment() {
        $.ajax({
            url: '/Departments/GetDepartmentByGroupId',
            method: 'POST',
            data: {
                DepartmentGroupId: $('#ddl_deptgroup').val(),
            },
            cache: false,
            error: function () {
                alert("An error occoured!");
            },
            success: function (response) {
                $('#ddl_dept').empty();
                $('#ddl_dept').append($('<option>', {
                    value: '',
                    text: '--All--'
                }));
                for (var i = 0; i < response.length; i++) {
                    var opt = new Option(response[i].Name, response[i].Sl);
                    $('#ddl_dept').append(opt);
                }
            }
        });
    };

    $(document).ready(function () {
        $('#myTable').DataTable();
    });

</script>

FTL_HRMS/Views/MonthlyAttendances/EmployeewiseAttendenceReport.cshtml
@model IEnumerable<FTL_HRMS.Models.Payroll.MonthlyAttendance>

@{
    ViewBag.Title = "Employee List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous">
</script>
@section scripts {
    <script src="~/Scripts/myScript.js" type="text/javascript"></script>
}
@using (Html.BeginForm())
{
    <header class="panel_header">
        <h2 class="title pull-left">Selection</h2>
        <div class="actions panel_actions pull-right">
            <i class="box_toggle fa fa-chevron-down"></i>
        </div>
    </header>
    <br /> <br />
    <div class="content-body">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="form-group">
                    <div class="col-md-4">
                        <label class="form-label" for="Fromdate">Employee Code Or Name</label>
                        <div>
                            <input type="hidden" id="EmployeeId" name="EmployeeId" />
                            <input type="text" id="EmployeeCode" value="" placeholder="Select Existing Employee" class="form-control" style="width:100%" />
                            @*@Html.DropDownList("EmployeeId", null, "--All--", htmlAttributes: new { @class = "form-control", style = "width:100%", @id = "employeeId", @name = "employeeId" })*@
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-label" for="Fromdate">From Date</label>
                            <div>
                                <input type="text" id="fromdate" name="FromDate" class="form-control datepicker" data-start-view="2" placeholder="mm/dd/yyyy" >
                            </div>
                        </div>
                     </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-label" for="Todate">To Date</label>
                            <div>
                                <input type="text" id="todate" name="ToDate" class="form-control datepicker" data-start-view="2" placeholder="mm/dd/yyyy" >
                            </div>
                        </div>
                       </div>
                    </div>
                  </div>
                    <div class="col-md-offset-2" style="margin-left:45%">
                        <input type="submit" value="Submit" name="Submit" class="btn btn-info" />
                    </div>
            </div>
        </div>

       
}
<header class="panel_header">
    <h2 class="title pull-left">Attend Employee's List</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>
<br /> <br />
<div class="content-body">
    <div class="row">
        <div class="col-md-1 text-right">
            <div class="btn-group">
                <button type="button" onclick="location.href='@Url.Action("PrintAttandanceByDateRangeReport", "Reports",new {EmployeeId= @ViewBag.EmpId, fromDate = @ViewBag.FromDate, toDate= @ViewBag.Todate })'" target="_blank" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-print"></span> Download PDF
                </button>
            </div>
        </div>
        <br /><br />
        <div class="col-md-12 col-sm-12 col-xs-12">
            @{int rowNo = 0;}
            <table id="myTable" class="table table-striped dt-responsive display" cellspacing="0" width="100%">

                <thead>
                    <tr>
                        <th style="text-align:center">SL</th>
                        <th data-priority="1" style="text-align:center">Date</th>
                        <th data-priority="1" style="text-align:center">Code</th>
                        <th data-priority="1" style="text-align:center">Name</th>
                        <th data-priority="3" style="text-align:center">Phone</th>
                        <th data-priority="1" style="text-align:center">Designation</th>
                        <th data-priority="6" style="text-align:center">Status</th>
                        <th style="text-align:center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td align="center" width="5%">
                                @(rowNo += 1)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Employee.Code)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Employee.Name)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Employee.Mobile)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Employee.Designation.Name)
                            </td>
                            <td width="10%" align="center">
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>

                            <td align="center" width="8%">
                                @if (item.Status == "A")
                                {
                                    <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("Edit", "MonthlyAttendances", new { id = item.Sl })'">Present</button>
                                }
                            </td>

                        </tr>
                    }

                </tbody>

            </table>

        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });

</script>

FTL_HRMS/Views/MonthlyAttendances/Index.cshtml
@model IEnumerable<FTL_HRMS.Models.Payroll.MonthlyAttendance>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Employee.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCalculated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsCalculated)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Sl }) |
            @Html.ActionLink("Details", "Details", new { id=item.Sl }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Sl })
        </td>
    </tr>
}

</table>

FTL_HRMS/Views/MonthlyAttendances/Synchronization.cshtml
@{
    ViewBag.Title = "Synchronization";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Synchronization</h1>
        </div>
    </div>
</div>

<div class="content-body col-lg-12 ">
    <div class="col-lg-6">
        <div class="btn-group col-md-offset-10">
            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("", "" )'">   Synchronize Device   </button><br />
            <p><font size="1">Last updated</font></p>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="btn-group">
            <button type="button" class="btn btn-primary btn-sm" aria-expanded="false" onclick="location.href='@Url.Action("", "" )'">Update Attendance</button>
            <p><font size="1">Last updated</font></p>
        </div>
    </div>
</div>